/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from './rx.module';
class NgxSerproRxModuleInjector extends import0.ɵNgModuleInjector<import1.NgxSerproRxModule> {
  _NgxSerproRxModule_0:import1.NgxSerproRxModule;
  constructor(parent:import0.Injector) {
    super(parent,([] as any[]),([] as any[]));
  }
  createInternal():import1.NgxSerproRxModule {
    this._NgxSerproRxModule_0 = new import1.NgxSerproRxModule();
    return this._NgxSerproRxModule_0;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import1.NgxSerproRxModule)) { return this._NgxSerproRxModule_0; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const NgxSerproRxModuleNgFactory:import0.NgModuleFactory<import1.NgxSerproRxModule> = new import0.NgModuleFactory<any>(NgxSerproRxModuleInjector,import1.NgxSerproRxModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvODAxMjk0OTg1NzIvZ2l0L3NlcnByby9ucG0tcGFja2FnZS9pbnBsYWNlLWxvYWRpbmctaW5kaWNhdG9yL3NyYy9yeC9yeC5tb2R1bGUubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vaG9tZS84MDEyOTQ5ODU3Mi9naXQvc2VycHJvL25wbS1wYWNrYWdlL2lucGxhY2UtbG9hZGluZy1pbmRpY2F0b3Ivc3JjL3J4L3J4Lm1vZHVsZS50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
